\input texinfo
@settitle Maniero - Personal blog, mostly about software engineering.

@copying
This is my personal blog.

Copyright @copyright{} 2025 Maniero.
@end copying

@titlepage
@title My website stack
@page
@insertcopying
@end titlepage

@contents

@node Top
@top Posts

These are my latest posts I hope you enjoy.

@node New blog
@chapter This is my new blog

Welcome to my new blog.  Since is a tradition to people talk about the stack
they choose for their blogs, I'll follow the same path.

@section Stack
There is nothing fancy
here. Just some sexy old school software.

As expected, this is a static website.
@url{https://www.gnu.org/software/texinfo/, GNU Texinfo} were used to generate
this pages.

@section Comments
The comment section is just mailing archive, there is a cron job that connects
into my email over SMTP and fetch emails related to the post.

During the deployment of this site, filters are configured in my email client
to automatically organize the emails into folders. And this folders are used to
display the comments bellow.

@section Look and feel
The blog style was inspired in how this page is rendered in the terminal using
@url{https://w3m.sourceforge.net/, w3m}. You can try it out:

@example bash
w3m https://maniero.me/New-blog.html
@end example

A fun fact about it is that while most of pages usually uses @code{px} or
@code{rem} are commonly used, the unit measure used in this blog is @code{ch}.

@bye
