\input texinfo
@settitle Maniero - Personal blog, mostly about software engineering.

@copying
This is my personal blog.

Copyright @copyright{} 2025 Maniero.
@end copying

@titlepage
@title My website stack
@page
@insertcopying
@end titlepage

@contents

@node Top
@top Posts

These are my latest posts I hope you enjoy.

@include posts/email-as-comments-backend.texi
@include posts/new-blog.texi
@include posts/teach-more-abstract-less.texi
@include posts/a-word-in-software-testing.texi

@bye
