name: Update Comments
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Testing
        env:
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |
          sudo apt-get install libnet-imap-* libemail-simple-perl libemail-mime-perl
          make

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: output
          CLEAN: true
